// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: handtracking.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Represents a 4x4 transformation matrix for a joint
public struct Handtracking_Matrix4x4: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var m00: Float = 0

  public var m01: Float = 0

  public var m02: Float = 0

  public var m03: Float = 0

  public var m10: Float = 0

  public var m11: Float = 0

  public var m12: Float = 0

  public var m13: Float = 0

  public var m20: Float = 0

  public var m21: Float = 0

  public var m22: Float = 0

  public var m23: Float = 0

  public var m30: Float = 0

  public var m31: Float = 0

  public var m32: Float = 0

  public var m33: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// The skeleton of a hand, comprising multiple 4x4 matrices (one per joint)
public struct Handtracking_Skeleton: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Array of 4x4 matrices, expecting 24 per hand based on your structure
  public var jointMatrices: [Handtracking_Matrix4x4] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// The hand tracking information, including the full 4x4 matrix for the wrist and the skeleton
public struct Handtracking_Hand: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 4x4 matrix for the wrist position and orientation
  public var wristMatrix: Handtracking_Matrix4x4 {
    get {return _storage._wristMatrix ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._wristMatrix = newValue}
  }
  /// Returns true if `wristMatrix` has been explicitly set.
  public var hasWristMatrix: Bool {return _storage._wristMatrix != nil}
  /// Clears the value of `wristMatrix`. Subsequent reads from it will return its default value.
  public mutating func clearWristMatrix() {_uniqueStorage()._wristMatrix = nil}

  /// The hand's skeleton
  public var skeleton: Handtracking_Skeleton {
    get {return _storage._skeleton ?? Handtracking_Skeleton()}
    set {_uniqueStorage()._skeleton = newValue}
  }
  /// Returns true if `skeleton` has been explicitly set.
  public var hasSkeleton: Bool {return _storage._skeleton != nil}
  /// Clears the value of `skeleton`. Subsequent reads from it will return its default value.
  public mutating func clearSkeleton() {_uniqueStorage()._skeleton = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// The overall hand update message, including data for both hands
public struct Handtracking_HandUpdate: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var leftHand: Handtracking_Hand {
    get {return _storage._leftHand ?? Handtracking_Hand()}
    set {_uniqueStorage()._leftHand = newValue}
  }
  /// Returns true if `leftHand` has been explicitly set.
  public var hasLeftHand: Bool {return _storage._leftHand != nil}
  /// Clears the value of `leftHand`. Subsequent reads from it will return its default value.
  public mutating func clearLeftHand() {_uniqueStorage()._leftHand = nil}

  public var rightHand: Handtracking_Hand {
    get {return _storage._rightHand ?? Handtracking_Hand()}
    set {_uniqueStorage()._rightHand = newValue}
  }
  /// Returns true if `rightHand` has been explicitly set.
  public var hasRightHand: Bool {return _storage._rightHand != nil}
  /// Clears the value of `rightHand`. Subsequent reads from it will return its default value.
  public mutating func clearRightHand() {_uniqueStorage()._rightHand = nil}

  public var head: Handtracking_Matrix4x4 {
    get {return _storage._head ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._head = newValue}
  }
  /// Returns true if `head` has been explicitly set.
  public var hasHead: Bool {return _storage._head != nil}
  /// Clears the value of `head`. Subsequent reads from it will return its default value.
  public mutating func clearHead() {_uniqueStorage()._head = nil}

  public var controllers: Handtracking_ControllerTracking {
    get {return _storage._controllers ?? Handtracking_ControllerTracking()}
    set {_uniqueStorage()._controllers = newValue}
  }
  /// Returns true if `controllers` has been explicitly set.
  public var hasControllers: Bool {return _storage._controllers != nil}
  /// Clears the value of `controllers`. Subsequent reads from it will return its default value.
  public mutating func clearControllers() {_uniqueStorage()._controllers = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Independent controller inputs. An inactive input is not a held/released value.
public struct Handtracking_ControllerInput: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var active: Bool = false

  public var isBoolean: Bool = false

  public var value: Float = 0

  public var pressed: Bool = false

  public var lastChangeTimeNs: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Handtracking_ControllerState: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Runtime action activity, not a Bluetooth connection guarantee.
  public var active: Bool {
    get {return _storage._active}
    set {_uniqueStorage()._active = newValue}
  }

  public var poseValid: Bool {
    get {return _storage._poseValid}
    set {_uniqueStorage()._poseValid = newValue}
  }

  /// Right-handed, meters, X right / Y up / -Z forward, in Surreal LOCAL space.
  public var pose: Handtracking_Matrix4x4 {
    get {return _storage._pose ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._pose = newValue}
  }
  /// Returns true if `pose` has been explicitly set.
  public var hasPose: Bool {return _storage._pose != nil}
  /// Clears the value of `pose`. Subsequent reads from it will return its default value.
  public mutating func clearPose() {_uniqueStorage()._pose = nil}

  public var inputs: [Handtracking_ControllerInput] {
    get {return _storage._inputs}
    set {_uniqueStorage()._inputs = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Handtracking_ControllerTracking: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var version: UInt32 {
    get {return _storage._version}
    set {_uniqueStorage()._version = newValue}
  }

  public var enabled: Bool {
    get {return _storage._enabled}
    set {_uniqueStorage()._enabled = newValue}
  }

  public var timestampNs: UInt64 {
    get {return _storage._timestampNs}
    set {_uniqueStorage()._timestampNs = newValue}
  }

  public var sequence: UInt64 {
    get {return _storage._sequence}
    set {_uniqueStorage()._sequence = newValue}
  }

  public var left: Handtracking_ControllerState {
    get {return _storage._left ?? Handtracking_ControllerState()}
    set {_uniqueStorage()._left = newValue}
  }
  /// Returns true if `left` has been explicitly set.
  public var hasLeft: Bool {return _storage._left != nil}
  /// Clears the value of `left`. Subsequent reads from it will return its default value.
  public mutating func clearLeft() {_uniqueStorage()._left = nil}

  public var right: Handtracking_ControllerState {
    get {return _storage._right ?? Handtracking_ControllerState()}
    set {_uniqueStorage()._right = newValue}
  }
  /// Returns true if `right` has been explicitly set.
  public var hasRight: Bool {return _storage._right != nil}
  /// Clears the value of `right`. Subsequent reads from it will return its default value.
  public mutating func clearRight() {_uniqueStorage()._right = nil}

  /// Raw ARKit worldFromHead, queried at timestamp_ns. No Python head-axis offset.
  public var headPose: Handtracking_Matrix4x4 {
    get {return _storage._headPose ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._headPose = newValue}
  }
  /// Returns true if `headPose` has been explicitly set.
  public var hasHeadPose: Bool {return _storage._headPose != nil}
  /// Clears the value of `headPose`. Subsequent reads from it will return its default value.
  public mutating func clearHeadPose() {_uniqueStorage()._headPose = nil}

  public var headPoseValid: Bool {
    get {return _storage._headPoseValid}
    set {_uniqueStorage()._headPoseValid = newValue}
  }

  public var source: String {
    get {return _storage._source}
    set {_uniqueStorage()._source = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Acknowledgement message for hand updates
public struct Handtracking_HandUpdateAck: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var message: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "handtracking"

extension Handtracking_Matrix4x4: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Matrix4x4"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}m00\0\u{1}m01\0\u{1}m02\0\u{1}m03\0\u{1}m10\0\u{1}m11\0\u{1}m12\0\u{1}m13\0\u{1}m20\0\u{1}m21\0\u{1}m22\0\u{1}m23\0\u{1}m30\0\u{1}m31\0\u{1}m32\0\u{1}m33\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.m00) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.m01) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.m02) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.m03) }()
      case 5: try { try decoder.decodeSingularFloatField(value: &self.m10) }()
      case 6: try { try decoder.decodeSingularFloatField(value: &self.m11) }()
      case 7: try { try decoder.decodeSingularFloatField(value: &self.m12) }()
      case 8: try { try decoder.decodeSingularFloatField(value: &self.m13) }()
      case 9: try { try decoder.decodeSingularFloatField(value: &self.m20) }()
      case 10: try { try decoder.decodeSingularFloatField(value: &self.m21) }()
      case 11: try { try decoder.decodeSingularFloatField(value: &self.m22) }()
      case 12: try { try decoder.decodeSingularFloatField(value: &self.m23) }()
      case 13: try { try decoder.decodeSingularFloatField(value: &self.m30) }()
      case 14: try { try decoder.decodeSingularFloatField(value: &self.m31) }()
      case 15: try { try decoder.decodeSingularFloatField(value: &self.m32) }()
      case 16: try { try decoder.decodeSingularFloatField(value: &self.m33) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.m00.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m00, fieldNumber: 1)
    }
    if self.m01.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m01, fieldNumber: 2)
    }
    if self.m02.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m02, fieldNumber: 3)
    }
    if self.m03.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m03, fieldNumber: 4)
    }
    if self.m10.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m10, fieldNumber: 5)
    }
    if self.m11.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m11, fieldNumber: 6)
    }
    if self.m12.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m12, fieldNumber: 7)
    }
    if self.m13.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m13, fieldNumber: 8)
    }
    if self.m20.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m20, fieldNumber: 9)
    }
    if self.m21.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m21, fieldNumber: 10)
    }
    if self.m22.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m22, fieldNumber: 11)
    }
    if self.m23.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m23, fieldNumber: 12)
    }
    if self.m30.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m30, fieldNumber: 13)
    }
    if self.m31.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m31, fieldNumber: 14)
    }
    if self.m32.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m32, fieldNumber: 15)
    }
    if self.m33.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m33, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_Matrix4x4, rhs: Handtracking_Matrix4x4) -> Bool {
    if lhs.m00 != rhs.m00 {return false}
    if lhs.m01 != rhs.m01 {return false}
    if lhs.m02 != rhs.m02 {return false}
    if lhs.m03 != rhs.m03 {return false}
    if lhs.m10 != rhs.m10 {return false}
    if lhs.m11 != rhs.m11 {return false}
    if lhs.m12 != rhs.m12 {return false}
    if lhs.m13 != rhs.m13 {return false}
    if lhs.m20 != rhs.m20 {return false}
    if lhs.m21 != rhs.m21 {return false}
    if lhs.m22 != rhs.m22 {return false}
    if lhs.m23 != rhs.m23 {return false}
    if lhs.m30 != rhs.m30 {return false}
    if lhs.m31 != rhs.m31 {return false}
    if lhs.m32 != rhs.m32 {return false}
    if lhs.m33 != rhs.m33 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_Skeleton: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Skeleton"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}jointMatrices\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.jointMatrices) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.jointMatrices.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.jointMatrices, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_Skeleton, rhs: Handtracking_Skeleton) -> Bool {
    if lhs.jointMatrices != rhs.jointMatrices {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_Hand: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Hand"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}wristMatrix\0\u{1}skeleton\0")

  fileprivate class _StorageClass {
    var _wristMatrix: Handtracking_Matrix4x4? = nil
    var _skeleton: Handtracking_Skeleton? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _wristMatrix = source._wristMatrix
      _skeleton = source._skeleton
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._wristMatrix) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._skeleton) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._wristMatrix {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._skeleton {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_Hand, rhs: Handtracking_Hand) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._wristMatrix != rhs_storage._wristMatrix {return false}
        if _storage._skeleton != rhs_storage._skeleton {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_HandUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HandUpdate"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}left_hand\0\u{3}right_hand\0\u{1}Head\0\u{1}controllers\0")

  fileprivate class _StorageClass {
    var _leftHand: Handtracking_Hand? = nil
    var _rightHand: Handtracking_Hand? = nil
    var _head: Handtracking_Matrix4x4? = nil
    var _controllers: Handtracking_ControllerTracking? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _leftHand = source._leftHand
      _rightHand = source._rightHand
      _head = source._head
      _controllers = source._controllers
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._leftHand) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._rightHand) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._head) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._controllers) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._leftHand {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._rightHand {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._head {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._controllers {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_HandUpdate, rhs: Handtracking_HandUpdate) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._leftHand != rhs_storage._leftHand {return false}
        if _storage._rightHand != rhs_storage._rightHand {return false}
        if _storage._head != rhs_storage._head {return false}
        if _storage._controllers != rhs_storage._controllers {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_ControllerInput: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ControllerInput"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}active\0\u{3}is_boolean\0\u{1}value\0\u{1}pressed\0\u{3}last_change_time_ns\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.active) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isBoolean) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.value) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.pressed) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.lastChangeTimeNs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.active != false {
      try visitor.visitSingularBoolField(value: self.active, fieldNumber: 2)
    }
    if self.isBoolean != false {
      try visitor.visitSingularBoolField(value: self.isBoolean, fieldNumber: 3)
    }
    if self.value.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.value, fieldNumber: 4)
    }
    if self.pressed != false {
      try visitor.visitSingularBoolField(value: self.pressed, fieldNumber: 5)
    }
    if self.lastChangeTimeNs != 0 {
      try visitor.visitSingularUInt64Field(value: self.lastChangeTimeNs, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_ControllerInput, rhs: Handtracking_ControllerInput) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.active != rhs.active {return false}
    if lhs.isBoolean != rhs.isBoolean {return false}
    if lhs.value != rhs.value {return false}
    if lhs.pressed != rhs.pressed {return false}
    if lhs.lastChangeTimeNs != rhs.lastChangeTimeNs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_ControllerState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ControllerState"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}active\0\u{3}pose_valid\0\u{1}pose\0\u{1}inputs\0")

  fileprivate class _StorageClass {
    var _active: Bool = false
    var _poseValid: Bool = false
    var _pose: Handtracking_Matrix4x4? = nil
    var _inputs: [Handtracking_ControllerInput] = []

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _active = source._active
      _poseValid = source._poseValid
      _pose = source._pose
      _inputs = source._inputs
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularBoolField(value: &_storage._active) }()
        case 2: try { try decoder.decodeSingularBoolField(value: &_storage._poseValid) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._pose) }()
        case 4: try { try decoder.decodeRepeatedMessageField(value: &_storage._inputs) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._active != false {
        try visitor.visitSingularBoolField(value: _storage._active, fieldNumber: 1)
      }
      if _storage._poseValid != false {
        try visitor.visitSingularBoolField(value: _storage._poseValid, fieldNumber: 2)
      }
      try { if let v = _storage._pose {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      if !_storage._inputs.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._inputs, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_ControllerState, rhs: Handtracking_ControllerState) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._active != rhs_storage._active {return false}
        if _storage._poseValid != rhs_storage._poseValid {return false}
        if _storage._pose != rhs_storage._pose {return false}
        if _storage._inputs != rhs_storage._inputs {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_ControllerTracking: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ControllerTracking"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}version\0\u{1}enabled\0\u{3}timestamp_ns\0\u{1}sequence\0\u{1}left\0\u{1}right\0\u{3}head_pose\0\u{3}head_pose_valid\0\u{1}source\0")

  fileprivate class _StorageClass {
    var _version: UInt32 = 0
    var _enabled: Bool = false
    var _timestampNs: UInt64 = 0
    var _sequence: UInt64 = 0
    var _left: Handtracking_ControllerState? = nil
    var _right: Handtracking_ControllerState? = nil
    var _headPose: Handtracking_Matrix4x4? = nil
    var _headPoseValid: Bool = false
    var _source: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _version = source._version
      _enabled = source._enabled
      _timestampNs = source._timestampNs
      _sequence = source._sequence
      _left = source._left
      _right = source._right
      _headPose = source._headPose
      _headPoseValid = source._headPoseValid
      _source = source._source
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt32Field(value: &_storage._version) }()
        case 2: try { try decoder.decodeSingularBoolField(value: &_storage._enabled) }()
        case 3: try { try decoder.decodeSingularUInt64Field(value: &_storage._timestampNs) }()
        case 4: try { try decoder.decodeSingularUInt64Field(value: &_storage._sequence) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._left) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._right) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._headPose) }()
        case 8: try { try decoder.decodeSingularBoolField(value: &_storage._headPoseValid) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._source) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._version != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._version, fieldNumber: 1)
      }
      if _storage._enabled != false {
        try visitor.visitSingularBoolField(value: _storage._enabled, fieldNumber: 2)
      }
      if _storage._timestampNs != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._timestampNs, fieldNumber: 3)
      }
      if _storage._sequence != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._sequence, fieldNumber: 4)
      }
      try { if let v = _storage._left {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._right {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._headPose {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      if _storage._headPoseValid != false {
        try visitor.visitSingularBoolField(value: _storage._headPoseValid, fieldNumber: 8)
      }
      if !_storage._source.isEmpty {
        try visitor.visitSingularStringField(value: _storage._source, fieldNumber: 9)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_ControllerTracking, rhs: Handtracking_ControllerTracking) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._version != rhs_storage._version {return false}
        if _storage._enabled != rhs_storage._enabled {return false}
        if _storage._timestampNs != rhs_storage._timestampNs {return false}
        if _storage._sequence != rhs_storage._sequence {return false}
        if _storage._left != rhs_storage._left {return false}
        if _storage._right != rhs_storage._right {return false}
        if _storage._headPose != rhs_storage._headPose {return false}
        if _storage._headPoseValid != rhs_storage._headPoseValid {return false}
        if _storage._source != rhs_storage._source {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_HandUpdateAck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HandUpdateAck"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}message\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_HandUpdateAck, rhs: Handtracking_HandUpdateAck) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
