// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: handtracking.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Represents a 4x4 transformation matrix for a joint
public struct Handtracking_Matrix4x4: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var m00: Float = 0

  public var m01: Float = 0

  public var m02: Float = 0

  public var m03: Float = 0

  public var m10: Float = 0

  public var m11: Float = 0

  public var m12: Float = 0

  public var m13: Float = 0

  public var m20: Float = 0

  public var m21: Float = 0

  public var m22: Float = 0

  public var m23: Float = 0

  public var m30: Float = 0

  public var m31: Float = 0

  public var m32: Float = 0

  public var m33: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// The skeleton of a hand, comprising multiple 4x4 matrices (one per joint)
public struct Handtracking_Skeleton: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Array of 4x4 matrices, expecting 24 per hand based on your structure
  public var jointMatrices: [Handtracking_Matrix4x4] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// The hand tracking information, including the full 4x4 matrix for the wrist and the skeleton
public struct Handtracking_Hand: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 4x4 matrix for the wrist position and orientation
  public var wristMatrix: Handtracking_Matrix4x4 {
    get {return _storage._wristMatrix ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._wristMatrix = newValue}
  }
  /// Returns true if `wristMatrix` has been explicitly set.
  public var hasWristMatrix: Bool {return _storage._wristMatrix != nil}
  /// Clears the value of `wristMatrix`. Subsequent reads from it will return its default value.
  public mutating func clearWristMatrix() {_uniqueStorage()._wristMatrix = nil}

  /// The hand's skeleton
  public var skeleton: Handtracking_Skeleton {
    get {return _storage._skeleton ?? Handtracking_Skeleton()}
    set {_uniqueStorage()._skeleton = newValue}
  }
  /// Returns true if `skeleton` has been explicitly set.
  public var hasSkeleton: Bool {return _storage._skeleton != nil}
  /// Clears the value of `skeleton`. Subsequent reads from it will return its default value.
  public mutating func clearSkeleton() {_uniqueStorage()._skeleton = nil}

  /// Zero means legacy sender: no tracking-validity guarantee.
  public var trackingVersion: UInt32 {
    get {return _storage._trackingVersion}
    set {_uniqueStorage()._trackingVersion = newValue}
  }

  public var tracked: Bool {
    get {return _storage._tracked}
    set {_uniqueStorage()._tracked = newValue}
  }

  public var sampleTimestampNs: UInt64 {
    get {return _storage._sampleTimestampNs}
    set {_uniqueStorage()._sampleTimestampNs = newValue}
  }

  public var sampleSequence: UInt64 {
    get {return _storage._sampleSequence}
    set {_uniqueStorage()._sampleSequence = newValue}
  }

  public var jointTracked: [Bool] {
    get {return _storage._jointTracked}
    set {_uniqueStorage()._jointTracked = newValue}
  }

  public var predictionMs: Float {
    get {return _storage._predictionMs}
    set {_uniqueStorage()._predictionMs = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// The overall hand update message, including data for both hands
public struct Handtracking_HandUpdate: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var leftHand: Handtracking_Hand {
    get {return _storage._leftHand ?? Handtracking_Hand()}
    set {_uniqueStorage()._leftHand = newValue}
  }
  /// Returns true if `leftHand` has been explicitly set.
  public var hasLeftHand: Bool {return _storage._leftHand != nil}
  /// Clears the value of `leftHand`. Subsequent reads from it will return its default value.
  public mutating func clearLeftHand() {_uniqueStorage()._leftHand = nil}

  public var rightHand: Handtracking_Hand {
    get {return _storage._rightHand ?? Handtracking_Hand()}
    set {_uniqueStorage()._rightHand = newValue}
  }
  /// Returns true if `rightHand` has been explicitly set.
  public var hasRightHand: Bool {return _storage._rightHand != nil}
  /// Clears the value of `rightHand`. Subsequent reads from it will return its default value.
  public mutating func clearRightHand() {_uniqueStorage()._rightHand = nil}

  public var head: Handtracking_Matrix4x4 {
    get {return _storage._head ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._head = newValue}
  }
  /// Returns true if `head` has been explicitly set.
  public var hasHead: Bool {return _storage._head != nil}
  /// Clears the value of `head`. Subsequent reads from it will return its default value.
  public mutating func clearHead() {_uniqueStorage()._head = nil}

  public var controllers: Handtracking_ControllerTracking {
    get {return _storage._controllers ?? Handtracking_ControllerTracking()}
    set {_uniqueStorage()._controllers = newValue}
  }
  /// Returns true if `controllers` has been explicitly set.
  public var hasControllers: Bool {return _storage._controllers != nil}
  /// Clears the value of `controllers`. Subsequent reads from it will return its default value.
  public mutating func clearControllers() {_uniqueStorage()._controllers = nil}

  /// serialization time in headset monotonic clock
  public var timestampNs: UInt64 {
    get {return _storage._timestampNs}
    set {_uniqueStorage()._timestampNs = newValue}
  }

  /// Changes on AR session restart and head tracking loss/relocalization.
  public var trackingSessionID: String {
    get {return _storage._trackingSessionID}
    set {_uniqueStorage()._trackingSessionID = newValue}
  }

  /// 1: session identity and optical validity
  public var trackingMetadataVersion: UInt32 {
    get {return _storage._trackingMetadataVersion}
    set {_uniqueStorage()._trackingMetadataVersion = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Independent controller inputs. An inactive input is not a held/released value.
public struct Handtracking_ControllerInput: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var active: Bool = false

  public var isBoolean: Bool = false

  public var value: Float = 0

  public var pressed: Bool = false

  public var lastChangeTimeNs: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Handtracking_ControllerState: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Runtime action activity, not a Bluetooth connection guarantee.
  public var active: Bool {
    get {return _storage._active}
    set {_uniqueStorage()._active = newValue}
  }

  public var poseValid: Bool {
    get {return _storage._poseValid}
    set {_uniqueStorage()._poseValid = newValue}
  }

  /// Right-handed, meters, X right / Y up / -Z forward, in Surreal LOCAL space.
  public var pose: Handtracking_Matrix4x4 {
    get {return _storage._pose ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._pose = newValue}
  }
  /// Returns true if `pose` has been explicitly set.
  public var hasPose: Bool {return _storage._pose != nil}
  /// Clears the value of `pose`. Subsequent reads from it will return its default value.
  public mutating func clearPose() {_uniqueStorage()._pose = nil}

  public var inputs: [Handtracking_ControllerInput] {
    get {return _storage._inputs}
    set {_uniqueStorage()._inputs = newValue}
  }

  /// Manually corrected ARKit worldFromGrip. Raw LOCAL pose remains in field 3.
  public var poseWorld: Handtracking_Matrix4x4 {
    get {return _storage._poseWorld ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._poseWorld = newValue}
  }
  /// Returns true if `poseWorld` has been explicitly set.
  public var hasPoseWorld: Bool {return _storage._poseWorld != nil}
  /// Clears the value of `poseWorld`. Subsequent reads from it will return its default value.
  public mutating func clearPoseWorld() {_uniqueStorage()._poseWorld = nil}

  /// Diagnostic only; never makes an invalid pose usable for tracking.
  public var poseStatus: String {
    get {return _storage._poseStatus}
    set {_uniqueStorage()._poseStatus = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Handtracking_ControllerCalibration: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var worldFromLocal: Handtracking_Matrix4x4 {
    get {return _storage._worldFromLocal ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._worldFromLocal = newValue}
  }
  /// Returns true if `worldFromLocal` has been explicitly set.
  public var hasWorldFromLocal: Bool {return _storage._worldFromLocal != nil}
  /// Clears the value of `worldFromLocal`. Subsequent reads from it will return its default value.
  public mutating func clearWorldFromLocal() {_uniqueStorage()._worldFromLocal = nil}

  public var leftGripOffset: Handtracking_Matrix4x4 {
    get {return _storage._leftGripOffset ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._leftGripOffset = newValue}
  }
  /// Returns true if `leftGripOffset` has been explicitly set.
  public var hasLeftGripOffset: Bool {return _storage._leftGripOffset != nil}
  /// Clears the value of `leftGripOffset`. Subsequent reads from it will return its default value.
  public mutating func clearLeftGripOffset() {_uniqueStorage()._leftGripOffset = nil}

  public var rightGripOffset: Handtracking_Matrix4x4 {
    get {return _storage._rightGripOffset ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._rightGripOffset = newValue}
  }
  /// Returns true if `rightGripOffset` has been explicitly set.
  public var hasRightGripOffset: Bool {return _storage._rightGripOffset != nil}
  /// Clears the value of `rightGripOffset`. Subsequent reads from it will return its default value.
  public mutating func clearRightGripOffset() {_uniqueStorage()._rightGripOffset = nil}

  public var saved: Bool {
    get {return _storage._saved}
    set {_uniqueStorage()._saved = newValue}
  }

  public var preview: Bool {
    get {return _storage._preview}
    set {_uniqueStorage()._preview = newValue}
  }

  public var reviewedThisSession: Bool {
    get {return _storage._reviewedThisSession}
    set {_uniqueStorage()._reviewedThisSession = newValue}
  }

  public var leftWristOffset: Handtracking_Matrix4x4 {
    get {return _storage._leftWristOffset ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._leftWristOffset = newValue}
  }
  /// Returns true if `leftWristOffset` has been explicitly set.
  public var hasLeftWristOffset: Bool {return _storage._leftWristOffset != nil}
  /// Clears the value of `leftWristOffset`. Subsequent reads from it will return its default value.
  public mutating func clearLeftWristOffset() {_uniqueStorage()._leftWristOffset = nil}

  public var rightWristOffset: Handtracking_Matrix4x4 {
    get {return _storage._rightWristOffset ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._rightWristOffset = newValue}
  }
  /// Returns true if `rightWristOffset` has been explicitly set.
  public var hasRightWristOffset: Bool {return _storage._rightWristOffset != nil}
  /// Clears the value of `rightWristOffset`. Subsequent reads from it will return its default value.
  public mutating func clearRightWristOffset() {_uniqueStorage()._rightWristOffset = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Handtracking_ControllerTracking: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var version: UInt32 {
    get {return _storage._version}
    set {_uniqueStorage()._version = newValue}
  }

  public var enabled: Bool {
    get {return _storage._enabled}
    set {_uniqueStorage()._enabled = newValue}
  }

  public var timestampNs: UInt64 {
    get {return _storage._timestampNs}
    set {_uniqueStorage()._timestampNs = newValue}
  }

  public var sequence: UInt64 {
    get {return _storage._sequence}
    set {_uniqueStorage()._sequence = newValue}
  }

  public var left: Handtracking_ControllerState {
    get {return _storage._left ?? Handtracking_ControllerState()}
    set {_uniqueStorage()._left = newValue}
  }
  /// Returns true if `left` has been explicitly set.
  public var hasLeft: Bool {return _storage._left != nil}
  /// Clears the value of `left`. Subsequent reads from it will return its default value.
  public mutating func clearLeft() {_uniqueStorage()._left = nil}

  public var right: Handtracking_ControllerState {
    get {return _storage._right ?? Handtracking_ControllerState()}
    set {_uniqueStorage()._right = newValue}
  }
  /// Returns true if `right` has been explicitly set.
  public var hasRight: Bool {return _storage._right != nil}
  /// Clears the value of `right`. Subsequent reads from it will return its default value.
  public mutating func clearRight() {_uniqueStorage()._right = nil}

  /// Raw ARKit worldFromHead, queried at timestamp_ns. No Python head-axis offset.
  public var headPose: Handtracking_Matrix4x4 {
    get {return _storage._headPose ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._headPose = newValue}
  }
  /// Returns true if `headPose` has been explicitly set.
  public var hasHeadPose: Bool {return _storage._headPose != nil}
  /// Clears the value of `headPose`. Subsequent reads from it will return its default value.
  public mutating func clearHeadPose() {_uniqueStorage()._headPose = nil}

  public var headPoseValid: Bool {
    get {return _storage._headPoseValid}
    set {_uniqueStorage()._headPoseValid = newValue}
  }

  public var source: String {
    get {return _storage._source}
    set {_uniqueStorage()._source = newValue}
  }

  public var calibration: Handtracking_ControllerCalibration {
    get {return _storage._calibration ?? Handtracking_ControllerCalibration()}
    set {_uniqueStorage()._calibration = newValue}
  }
  /// Returns true if `calibration` has been explicitly set.
  public var hasCalibration: Bool {return _storage._calibration != nil}
  /// Clears the value of `calibration`. Subsequent reads from it will return its default value.
  public mutating func clearCalibration() {_uniqueStorage()._calibration = nil}

  public var gloves: Handtracking_WujiGloveTracking {
    get {return _storage._gloves ?? Handtracking_WujiGloveTracking()}
    set {_uniqueStorage()._gloves = newValue}
  }
  /// Returns true if `gloves` has been explicitly set.
  public var hasGloves: Bool {return _storage._gloves != nil}
  /// Clears the value of `gloves`. Subsequent reads from it will return its default value.
  public mutating func clearGloves() {_uniqueStorage()._gloves = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Acknowledgement message for hand updates
public struct Handtracking_HandUpdateAck: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var message: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Glove skeletons stay distinct from ARKit optical hands. Positions are meters.
public struct Handtracking_WujiGloveState: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var valid: Bool {
    get {return _storage._valid}
    set {_uniqueStorage()._valid = newValue}
  }

  public var status: String {
    get {return _storage._status}
    set {_uniqueStorage()._status = newValue}
  }

  public var serial: String {
    get {return _storage._serial}
    set {_uniqueStorage()._serial = newValue}
  }

  public var sequence: UInt64 {
    get {return _storage._sequence}
    set {_uniqueStorage()._sequence = newValue}
  }

  public var sourceTimestampUs: UInt64 {
    get {return _storage._sourceTimestampUs}
    set {_uniqueStorage()._sourceTimestampUs = newValue}
  }

  /// capture time mapped to headset monotonic clock
  public var timestampNs: UInt64 {
    get {return _storage._timestampNs}
    set {_uniqueStorage()._timestampNs = newValue}
  }

  /// estimated sync error, not a measured guarantee
  public var uncertaintyMs: Float {
    get {return _storage._uncertaintyMs}
    set {_uniqueStorage()._uncertaintyMs = newValue}
  }

  /// 21 xyz triples, MediaPipe order
  public var pointsWrist: [Float] {
    get {return _storage._pointsWrist}
    set {_uniqueStorage()._pointsWrist = newValue}
  }

  public var confidence: [Float] {
    get {return _storage._confidence}
    set {_uniqueStorage()._confidence = newValue}
  }

  public var wristWorld: Handtracking_Matrix4x4 {
    get {return _storage._wristWorld ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._wristWorld = newValue}
  }
  /// Returns true if `wristWorld` has been explicitly set.
  public var hasWristWorld: Bool {return _storage._wristWorld != nil}
  /// Clears the value of `wristWorld`. Subsequent reads from it will return its default value.
  public mutating func clearWristWorld() {_uniqueStorage()._wristWorld = nil}

  /// interpolated at the same capture time
  public var headWorld: Handtracking_Matrix4x4 {
    get {return _storage._headWorld ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._headWorld = newValue}
  }
  /// Returns true if `headWorld` has been explicitly set.
  public var hasHeadWorld: Bool {return _storage._headWorld != nil}
  /// Clears the value of `headWorld`. Subsequent reads from it will return its default value.
  public mutating func clearHeadWorld() {_uniqueStorage()._headWorld = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Handtracking_WujiGloveTracking: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var version: UInt32 = 0

  public var left: Handtracking_WujiGloveState {
    get {return _left ?? Handtracking_WujiGloveState()}
    set {_left = newValue}
  }
  /// Returns true if `left` has been explicitly set.
  public var hasLeft: Bool {return self._left != nil}
  /// Clears the value of `left`. Subsequent reads from it will return its default value.
  public mutating func clearLeft() {self._left = nil}

  public var right: Handtracking_WujiGloveState {
    get {return _right ?? Handtracking_WujiGloveState()}
    set {_right = newValue}
  }
  /// Returns true if `right` has been explicitly set.
  public var hasRight: Bool {return self._right != nil}
  /// Clears the value of `right`. Subsequent reads from it will return its default value.
  public mutating func clearRight() {self._right = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _left: Handtracking_WujiGloveState? = nil
  fileprivate var _right: Handtracking_WujiGloveState? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "handtracking"

extension Handtracking_Matrix4x4: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Matrix4x4"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}m00\0\u{1}m01\0\u{1}m02\0\u{1}m03\0\u{1}m10\0\u{1}m11\0\u{1}m12\0\u{1}m13\0\u{1}m20\0\u{1}m21\0\u{1}m22\0\u{1}m23\0\u{1}m30\0\u{1}m31\0\u{1}m32\0\u{1}m33\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.m00) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.m01) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.m02) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.m03) }()
      case 5: try { try decoder.decodeSingularFloatField(value: &self.m10) }()
      case 6: try { try decoder.decodeSingularFloatField(value: &self.m11) }()
      case 7: try { try decoder.decodeSingularFloatField(value: &self.m12) }()
      case 8: try { try decoder.decodeSingularFloatField(value: &self.m13) }()
      case 9: try { try decoder.decodeSingularFloatField(value: &self.m20) }()
      case 10: try { try decoder.decodeSingularFloatField(value: &self.m21) }()
      case 11: try { try decoder.decodeSingularFloatField(value: &self.m22) }()
      case 12: try { try decoder.decodeSingularFloatField(value: &self.m23) }()
      case 13: try { try decoder.decodeSingularFloatField(value: &self.m30) }()
      case 14: try { try decoder.decodeSingularFloatField(value: &self.m31) }()
      case 15: try { try decoder.decodeSingularFloatField(value: &self.m32) }()
      case 16: try { try decoder.decodeSingularFloatField(value: &self.m33) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.m00.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m00, fieldNumber: 1)
    }
    if self.m01.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m01, fieldNumber: 2)
    }
    if self.m02.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m02, fieldNumber: 3)
    }
    if self.m03.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m03, fieldNumber: 4)
    }
    if self.m10.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m10, fieldNumber: 5)
    }
    if self.m11.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m11, fieldNumber: 6)
    }
    if self.m12.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m12, fieldNumber: 7)
    }
    if self.m13.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m13, fieldNumber: 8)
    }
    if self.m20.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m20, fieldNumber: 9)
    }
    if self.m21.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m21, fieldNumber: 10)
    }
    if self.m22.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m22, fieldNumber: 11)
    }
    if self.m23.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m23, fieldNumber: 12)
    }
    if self.m30.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m30, fieldNumber: 13)
    }
    if self.m31.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m31, fieldNumber: 14)
    }
    if self.m32.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m32, fieldNumber: 15)
    }
    if self.m33.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m33, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_Matrix4x4, rhs: Handtracking_Matrix4x4) -> Bool {
    if lhs.m00 != rhs.m00 {return false}
    if lhs.m01 != rhs.m01 {return false}
    if lhs.m02 != rhs.m02 {return false}
    if lhs.m03 != rhs.m03 {return false}
    if lhs.m10 != rhs.m10 {return false}
    if lhs.m11 != rhs.m11 {return false}
    if lhs.m12 != rhs.m12 {return false}
    if lhs.m13 != rhs.m13 {return false}
    if lhs.m20 != rhs.m20 {return false}
    if lhs.m21 != rhs.m21 {return false}
    if lhs.m22 != rhs.m22 {return false}
    if lhs.m23 != rhs.m23 {return false}
    if lhs.m30 != rhs.m30 {return false}
    if lhs.m31 != rhs.m31 {return false}
    if lhs.m32 != rhs.m32 {return false}
    if lhs.m33 != rhs.m33 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_Skeleton: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Skeleton"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}jointMatrices\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.jointMatrices) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.jointMatrices.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.jointMatrices, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_Skeleton, rhs: Handtracking_Skeleton) -> Bool {
    if lhs.jointMatrices != rhs.jointMatrices {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_Hand: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Hand"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}wristMatrix\0\u{1}skeleton\0\u{3}tracking_version\0\u{1}tracked\0\u{3}sample_timestamp_ns\0\u{3}sample_sequence\0\u{3}joint_tracked\0\u{3}prediction_ms\0")

  fileprivate class _StorageClass {
    var _wristMatrix: Handtracking_Matrix4x4? = nil
    var _skeleton: Handtracking_Skeleton? = nil
    var _trackingVersion: UInt32 = 0
    var _tracked: Bool = false
    var _sampleTimestampNs: UInt64 = 0
    var _sampleSequence: UInt64 = 0
    var _jointTracked: [Bool] = []
    var _predictionMs: Float = 0

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _wristMatrix = source._wristMatrix
      _skeleton = source._skeleton
      _trackingVersion = source._trackingVersion
      _tracked = source._tracked
      _sampleTimestampNs = source._sampleTimestampNs
      _sampleSequence = source._sampleSequence
      _jointTracked = source._jointTracked
      _predictionMs = source._predictionMs
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._wristMatrix) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._skeleton) }()
        case 3: try { try decoder.decodeSingularUInt32Field(value: &_storage._trackingVersion) }()
        case 4: try { try decoder.decodeSingularBoolField(value: &_storage._tracked) }()
        case 5: try { try decoder.decodeSingularUInt64Field(value: &_storage._sampleTimestampNs) }()
        case 6: try { try decoder.decodeSingularUInt64Field(value: &_storage._sampleSequence) }()
        case 7: try { try decoder.decodeRepeatedBoolField(value: &_storage._jointTracked) }()
        case 8: try { try decoder.decodeSingularFloatField(value: &_storage._predictionMs) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._wristMatrix {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._skeleton {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      if _storage._trackingVersion != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._trackingVersion, fieldNumber: 3)
      }
      if _storage._tracked != false {
        try visitor.visitSingularBoolField(value: _storage._tracked, fieldNumber: 4)
      }
      if _storage._sampleTimestampNs != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._sampleTimestampNs, fieldNumber: 5)
      }
      if _storage._sampleSequence != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._sampleSequence, fieldNumber: 6)
      }
      if !_storage._jointTracked.isEmpty {
        try visitor.visitPackedBoolField(value: _storage._jointTracked, fieldNumber: 7)
      }
      if _storage._predictionMs.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._predictionMs, fieldNumber: 8)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_Hand, rhs: Handtracking_Hand) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._wristMatrix != rhs_storage._wristMatrix {return false}
        if _storage._skeleton != rhs_storage._skeleton {return false}
        if _storage._trackingVersion != rhs_storage._trackingVersion {return false}
        if _storage._tracked != rhs_storage._tracked {return false}
        if _storage._sampleTimestampNs != rhs_storage._sampleTimestampNs {return false}
        if _storage._sampleSequence != rhs_storage._sampleSequence {return false}
        if _storage._jointTracked != rhs_storage._jointTracked {return false}
        if _storage._predictionMs != rhs_storage._predictionMs {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_HandUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HandUpdate"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}left_hand\0\u{3}right_hand\0\u{1}Head\0\u{1}controllers\0\u{3}timestamp_ns\0\u{3}tracking_session_id\0\u{3}tracking_metadata_version\0")

  fileprivate class _StorageClass {
    var _leftHand: Handtracking_Hand? = nil
    var _rightHand: Handtracking_Hand? = nil
    var _head: Handtracking_Matrix4x4? = nil
    var _controllers: Handtracking_ControllerTracking? = nil
    var _timestampNs: UInt64 = 0
    var _trackingSessionID: String = String()
    var _trackingMetadataVersion: UInt32 = 0

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _leftHand = source._leftHand
      _rightHand = source._rightHand
      _head = source._head
      _controllers = source._controllers
      _timestampNs = source._timestampNs
      _trackingSessionID = source._trackingSessionID
      _trackingMetadataVersion = source._trackingMetadataVersion
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._leftHand) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._rightHand) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._head) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._controllers) }()
        case 5: try { try decoder.decodeSingularUInt64Field(value: &_storage._timestampNs) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._trackingSessionID) }()
        case 7: try { try decoder.decodeSingularUInt32Field(value: &_storage._trackingMetadataVersion) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._leftHand {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._rightHand {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._head {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._controllers {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      if _storage._timestampNs != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._timestampNs, fieldNumber: 5)
      }
      if !_storage._trackingSessionID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._trackingSessionID, fieldNumber: 6)
      }
      if _storage._trackingMetadataVersion != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._trackingMetadataVersion, fieldNumber: 7)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_HandUpdate, rhs: Handtracking_HandUpdate) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._leftHand != rhs_storage._leftHand {return false}
        if _storage._rightHand != rhs_storage._rightHand {return false}
        if _storage._head != rhs_storage._head {return false}
        if _storage._controllers != rhs_storage._controllers {return false}
        if _storage._timestampNs != rhs_storage._timestampNs {return false}
        if _storage._trackingSessionID != rhs_storage._trackingSessionID {return false}
        if _storage._trackingMetadataVersion != rhs_storage._trackingMetadataVersion {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_ControllerInput: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ControllerInput"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}active\0\u{3}is_boolean\0\u{1}value\0\u{1}pressed\0\u{3}last_change_time_ns\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.active) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isBoolean) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.value) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.pressed) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.lastChangeTimeNs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.active != false {
      try visitor.visitSingularBoolField(value: self.active, fieldNumber: 2)
    }
    if self.isBoolean != false {
      try visitor.visitSingularBoolField(value: self.isBoolean, fieldNumber: 3)
    }
    if self.value.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.value, fieldNumber: 4)
    }
    if self.pressed != false {
      try visitor.visitSingularBoolField(value: self.pressed, fieldNumber: 5)
    }
    if self.lastChangeTimeNs != 0 {
      try visitor.visitSingularUInt64Field(value: self.lastChangeTimeNs, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_ControllerInput, rhs: Handtracking_ControllerInput) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.active != rhs.active {return false}
    if lhs.isBoolean != rhs.isBoolean {return false}
    if lhs.value != rhs.value {return false}
    if lhs.pressed != rhs.pressed {return false}
    if lhs.lastChangeTimeNs != rhs.lastChangeTimeNs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_ControllerState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ControllerState"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}active\0\u{3}pose_valid\0\u{1}pose\0\u{1}inputs\0\u{3}pose_world\0\u{3}pose_status\0")

  fileprivate class _StorageClass {
    var _active: Bool = false
    var _poseValid: Bool = false
    var _pose: Handtracking_Matrix4x4? = nil
    var _inputs: [Handtracking_ControllerInput] = []
    var _poseWorld: Handtracking_Matrix4x4? = nil
    var _poseStatus: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _active = source._active
      _poseValid = source._poseValid
      _pose = source._pose
      _inputs = source._inputs
      _poseWorld = source._poseWorld
      _poseStatus = source._poseStatus
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularBoolField(value: &_storage._active) }()
        case 2: try { try decoder.decodeSingularBoolField(value: &_storage._poseValid) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._pose) }()
        case 4: try { try decoder.decodeRepeatedMessageField(value: &_storage._inputs) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._poseWorld) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._poseStatus) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._active != false {
        try visitor.visitSingularBoolField(value: _storage._active, fieldNumber: 1)
      }
      if _storage._poseValid != false {
        try visitor.visitSingularBoolField(value: _storage._poseValid, fieldNumber: 2)
      }
      try { if let v = _storage._pose {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      if !_storage._inputs.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._inputs, fieldNumber: 4)
      }
      try { if let v = _storage._poseWorld {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      if !_storage._poseStatus.isEmpty {
        try visitor.visitSingularStringField(value: _storage._poseStatus, fieldNumber: 6)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_ControllerState, rhs: Handtracking_ControllerState) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._active != rhs_storage._active {return false}
        if _storage._poseValid != rhs_storage._poseValid {return false}
        if _storage._pose != rhs_storage._pose {return false}
        if _storage._inputs != rhs_storage._inputs {return false}
        if _storage._poseWorld != rhs_storage._poseWorld {return false}
        if _storage._poseStatus != rhs_storage._poseStatus {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_ControllerCalibration: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ControllerCalibration"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}world_from_local\0\u{3}left_grip_offset\0\u{3}right_grip_offset\0\u{1}saved\0\u{1}preview\0\u{3}reviewed_this_session\0\u{3}left_wrist_offset\0\u{3}right_wrist_offset\0")

  fileprivate class _StorageClass {
    var _worldFromLocal: Handtracking_Matrix4x4? = nil
    var _leftGripOffset: Handtracking_Matrix4x4? = nil
    var _rightGripOffset: Handtracking_Matrix4x4? = nil
    var _saved: Bool = false
    var _preview: Bool = false
    var _reviewedThisSession: Bool = false
    var _leftWristOffset: Handtracking_Matrix4x4? = nil
    var _rightWristOffset: Handtracking_Matrix4x4? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _worldFromLocal = source._worldFromLocal
      _leftGripOffset = source._leftGripOffset
      _rightGripOffset = source._rightGripOffset
      _saved = source._saved
      _preview = source._preview
      _reviewedThisSession = source._reviewedThisSession
      _leftWristOffset = source._leftWristOffset
      _rightWristOffset = source._rightWristOffset
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._worldFromLocal) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._leftGripOffset) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._rightGripOffset) }()
        case 4: try { try decoder.decodeSingularBoolField(value: &_storage._saved) }()
        case 5: try { try decoder.decodeSingularBoolField(value: &_storage._preview) }()
        case 6: try { try decoder.decodeSingularBoolField(value: &_storage._reviewedThisSession) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._leftWristOffset) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._rightWristOffset) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._worldFromLocal {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._leftGripOffset {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._rightGripOffset {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      if _storage._saved != false {
        try visitor.visitSingularBoolField(value: _storage._saved, fieldNumber: 4)
      }
      if _storage._preview != false {
        try visitor.visitSingularBoolField(value: _storage._preview, fieldNumber: 5)
      }
      if _storage._reviewedThisSession != false {
        try visitor.visitSingularBoolField(value: _storage._reviewedThisSession, fieldNumber: 6)
      }
      try { if let v = _storage._leftWristOffset {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._rightWristOffset {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_ControllerCalibration, rhs: Handtracking_ControllerCalibration) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._worldFromLocal != rhs_storage._worldFromLocal {return false}
        if _storage._leftGripOffset != rhs_storage._leftGripOffset {return false}
        if _storage._rightGripOffset != rhs_storage._rightGripOffset {return false}
        if _storage._saved != rhs_storage._saved {return false}
        if _storage._preview != rhs_storage._preview {return false}
        if _storage._reviewedThisSession != rhs_storage._reviewedThisSession {return false}
        if _storage._leftWristOffset != rhs_storage._leftWristOffset {return false}
        if _storage._rightWristOffset != rhs_storage._rightWristOffset {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_ControllerTracking: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ControllerTracking"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}version\0\u{1}enabled\0\u{3}timestamp_ns\0\u{1}sequence\0\u{1}left\0\u{1}right\0\u{3}head_pose\0\u{3}head_pose_valid\0\u{1}source\0\u{1}calibration\0\u{1}gloves\0")

  fileprivate class _StorageClass {
    var _version: UInt32 = 0
    var _enabled: Bool = false
    var _timestampNs: UInt64 = 0
    var _sequence: UInt64 = 0
    var _left: Handtracking_ControllerState? = nil
    var _right: Handtracking_ControllerState? = nil
    var _headPose: Handtracking_Matrix4x4? = nil
    var _headPoseValid: Bool = false
    var _source: String = String()
    var _calibration: Handtracking_ControllerCalibration? = nil
    var _gloves: Handtracking_WujiGloveTracking? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _version = source._version
      _enabled = source._enabled
      _timestampNs = source._timestampNs
      _sequence = source._sequence
      _left = source._left
      _right = source._right
      _headPose = source._headPose
      _headPoseValid = source._headPoseValid
      _source = source._source
      _calibration = source._calibration
      _gloves = source._gloves
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt32Field(value: &_storage._version) }()
        case 2: try { try decoder.decodeSingularBoolField(value: &_storage._enabled) }()
        case 3: try { try decoder.decodeSingularUInt64Field(value: &_storage._timestampNs) }()
        case 4: try { try decoder.decodeSingularUInt64Field(value: &_storage._sequence) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._left) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._right) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._headPose) }()
        case 8: try { try decoder.decodeSingularBoolField(value: &_storage._headPoseValid) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._source) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._calibration) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._gloves) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._version != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._version, fieldNumber: 1)
      }
      if _storage._enabled != false {
        try visitor.visitSingularBoolField(value: _storage._enabled, fieldNumber: 2)
      }
      if _storage._timestampNs != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._timestampNs, fieldNumber: 3)
      }
      if _storage._sequence != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._sequence, fieldNumber: 4)
      }
      try { if let v = _storage._left {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._right {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._headPose {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      if _storage._headPoseValid != false {
        try visitor.visitSingularBoolField(value: _storage._headPoseValid, fieldNumber: 8)
      }
      if !_storage._source.isEmpty {
        try visitor.visitSingularStringField(value: _storage._source, fieldNumber: 9)
      }
      try { if let v = _storage._calibration {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._gloves {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_ControllerTracking, rhs: Handtracking_ControllerTracking) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._version != rhs_storage._version {return false}
        if _storage._enabled != rhs_storage._enabled {return false}
        if _storage._timestampNs != rhs_storage._timestampNs {return false}
        if _storage._sequence != rhs_storage._sequence {return false}
        if _storage._left != rhs_storage._left {return false}
        if _storage._right != rhs_storage._right {return false}
        if _storage._headPose != rhs_storage._headPose {return false}
        if _storage._headPoseValid != rhs_storage._headPoseValid {return false}
        if _storage._source != rhs_storage._source {return false}
        if _storage._calibration != rhs_storage._calibration {return false}
        if _storage._gloves != rhs_storage._gloves {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_HandUpdateAck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HandUpdateAck"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}message\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_HandUpdateAck, rhs: Handtracking_HandUpdateAck) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_WujiGloveState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WujiGloveState"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}valid\0\u{1}status\0\u{1}serial\0\u{1}sequence\0\u{3}source_timestamp_us\0\u{3}timestamp_ns\0\u{3}uncertainty_ms\0\u{3}points_wrist\0\u{1}confidence\0\u{3}wrist_world\0\u{3}head_world\0")

  fileprivate class _StorageClass {
    var _valid: Bool = false
    var _status: String = String()
    var _serial: String = String()
    var _sequence: UInt64 = 0
    var _sourceTimestampUs: UInt64 = 0
    var _timestampNs: UInt64 = 0
    var _uncertaintyMs: Float = 0
    var _pointsWrist: [Float] = []
    var _confidence: [Float] = []
    var _wristWorld: Handtracking_Matrix4x4? = nil
    var _headWorld: Handtracking_Matrix4x4? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _valid = source._valid
      _status = source._status
      _serial = source._serial
      _sequence = source._sequence
      _sourceTimestampUs = source._sourceTimestampUs
      _timestampNs = source._timestampNs
      _uncertaintyMs = source._uncertaintyMs
      _pointsWrist = source._pointsWrist
      _confidence = source._confidence
      _wristWorld = source._wristWorld
      _headWorld = source._headWorld
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularBoolField(value: &_storage._valid) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._status) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._serial) }()
        case 4: try { try decoder.decodeSingularUInt64Field(value: &_storage._sequence) }()
        case 5: try { try decoder.decodeSingularUInt64Field(value: &_storage._sourceTimestampUs) }()
        case 6: try { try decoder.decodeSingularUInt64Field(value: &_storage._timestampNs) }()
        case 7: try { try decoder.decodeSingularFloatField(value: &_storage._uncertaintyMs) }()
        case 8: try { try decoder.decodeRepeatedFloatField(value: &_storage._pointsWrist) }()
        case 9: try { try decoder.decodeRepeatedFloatField(value: &_storage._confidence) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._wristWorld) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._headWorld) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._valid != false {
        try visitor.visitSingularBoolField(value: _storage._valid, fieldNumber: 1)
      }
      if !_storage._status.isEmpty {
        try visitor.visitSingularStringField(value: _storage._status, fieldNumber: 2)
      }
      if !_storage._serial.isEmpty {
        try visitor.visitSingularStringField(value: _storage._serial, fieldNumber: 3)
      }
      if _storage._sequence != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._sequence, fieldNumber: 4)
      }
      if _storage._sourceTimestampUs != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._sourceTimestampUs, fieldNumber: 5)
      }
      if _storage._timestampNs != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._timestampNs, fieldNumber: 6)
      }
      if _storage._uncertaintyMs.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._uncertaintyMs, fieldNumber: 7)
      }
      if !_storage._pointsWrist.isEmpty {
        try visitor.visitPackedFloatField(value: _storage._pointsWrist, fieldNumber: 8)
      }
      if !_storage._confidence.isEmpty {
        try visitor.visitPackedFloatField(value: _storage._confidence, fieldNumber: 9)
      }
      try { if let v = _storage._wristWorld {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._headWorld {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_WujiGloveState, rhs: Handtracking_WujiGloveState) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._valid != rhs_storage._valid {return false}
        if _storage._status != rhs_storage._status {return false}
        if _storage._serial != rhs_storage._serial {return false}
        if _storage._sequence != rhs_storage._sequence {return false}
        if _storage._sourceTimestampUs != rhs_storage._sourceTimestampUs {return false}
        if _storage._timestampNs != rhs_storage._timestampNs {return false}
        if _storage._uncertaintyMs != rhs_storage._uncertaintyMs {return false}
        if _storage._pointsWrist != rhs_storage._pointsWrist {return false}
        if _storage._confidence != rhs_storage._confidence {return false}
        if _storage._wristWorld != rhs_storage._wristWorld {return false}
        if _storage._headWorld != rhs_storage._headWorld {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_WujiGloveTracking: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WujiGloveTracking"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}version\0\u{1}left\0\u{1}right\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.version) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._left) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._right) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.version != 0 {
      try visitor.visitSingularUInt32Field(value: self.version, fieldNumber: 1)
    }
    try { if let v = self._left {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._right {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_WujiGloveTracking, rhs: Handtracking_WujiGloveTracking) -> Bool {
    if lhs.version != rhs.version {return false}
    if lhs._left != rhs._left {return false}
    if lhs._right != rhs._right {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
